version: '3'
services:
  web:
    build: .
    environment:
      - DB_NAME=db
    ports:
    - "5000:5000"
    depends_on:
    - db
    networks:
      - backend
  db:
    image: mongo:4.0.9
    ports:
      - "27018:27017"
    networks:
      - backend
networks:
  backend: